### ISSUE TITLE
Tag OONI Pipeline v5 alpha

### ISSUE THREAD

**Issue by hellais** [ooni/data#66]
It's about time we stamp an alpha tag for OONI Pipeline v5.

Here is a checklist of what I would like to have done in order to call it an alpha.

### Todo list
* [x] Polish the CLI and update relevant docs with the new CLI usage information
* [x] Refactor the activities and workflows (see [temporalio/samples-python](https://github.com/temporalio/samples-python))
     * [x]  evaluate [idempotency of activities](https://docs.temporal.io/activities#idempotency)
     * [x] restructure [workflows](https://docs.temporal.io/workflows) to properly encapsulate dependencies
* [x] Implement [workflow scheduling](https://docs.temporal.io/workflows#schedule) (see [sample](https://github.com/temporalio/samples-python/tree/main/schedules))
* [x] More extensive testing and review of the analysis and fix any bugs found
    * [x] Reach 80% code coverage (we [now have 87% coverage](https://github.com/ooni/data/pull/64#issuecomment-2074833048))

### Stretch goals
* [ ] Land web connectivity 0.5 support: https://github.com/ooni/data/issues/39
* [ ] If we are happy enough with temporal, close https://github.com/ooni/data/issues/46
* [x] https://github.com/ooni/data/issues/65
* [ ] Add support for running on temporal cloud (currently blocking on getting our sponsored account activated by the temporal team)
* [ ] https://github.com/ooni/data/issues/54
* [ ] Port response archiver to temporal
* [ ] Port fingerprint hunter to temporal

If the stretch goals are not completed, we should migrate them over to separate issues.

### Useful references for best practices
* https://github.com/temporalio/samples-python/blob/main/cloud_export_to_parquet/workflows.py
* https://github.com/PostHog/posthog/tree/master/posthog/temporal
